name: 'Testing inputs'

on:
  workflow_dispatch:
    inputs:
      full_name:
        description: 'Your name'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $INPUT_FULL_NAME